[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/',
]

[lint]
exclude_lints = ["screaming-snake-case-immutable", "mixed-case-variable"]
